### ISSUE TITLE
[BUG] SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by sdancer75** [formio/formio-upload#15]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: chrome
- Browser version:

## Steps to Reproduce
1.  Just a simple text file upload
2. 
3. 

## Expected behavior
To upload the file
## Observed behavior
Crash on the process
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

Full Debug report below
```js


  express:router:route post '/file' +1ms
  express:router:layer new '/' +0ms
File Upload Proxy Listening on 4100
  express:router dispatching OPTIONS /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +9s
  express:router query  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +1ms
  express:router expressInit  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +3ms
  express:router corsMiddleware  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +0ms
  express:router dispatching POST /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +14ms
  express:router query  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +0ms
  express:router expressInit  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +0ms
  express:router corsMiddleware  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +1ms
  express:router jsonParser  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +0ms
  body-parser:json content-type "multipart/form-data; boundary=----WebKitFormBoundary68wCIkA2n3fCzaXW" +0ms
  body-parser:json skip parsing +2ms
  express:router methodOverride  : /file?baseUrl=https%3A%2F%2Fdev-thess.pde.sch.gr%2Fformio&project=undefined&form=620b78c0df278801208dc5e4 +2ms
  upload 298111ec-0749-40ae-bb32-328603304d0b: New Request from undefined: (::1) +0ms  upload 298111ec-0749-40ae-bb32-328603304d0b: Authenticating +1ms
undefined:1
<!doctype html><html ng-app="formioApp"><head><meta charset="utf-8"><title>Form.io: The combined Form and API platform.</title><meta name="description" content=""><meta name="viewport" content="width=device-width"><link href="https://fonts.googleapis.com/css?family=Vast+Shadow" rel="stylesheet" type="text/css"><script src="https://maps.google.com/maps/api/js"></script><script src="//cdn.ckeditor.com/4.7.1/full/ckeditor.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/ace.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/ext-language_tools.js"></script><link rel="stylesheet" href="styles/app-86bcba9989.css"><link rel="stylesheet" href="styles/vendor-0ffa131bfe.css"></head><body><!--[if lt IE 10]>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/mnt/d/git_projects/formioupload/middleware/auth.js:69:34)
    at Request.self.callback (/mnt/d/git_projects/formioupload/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/mnt/d/git_projects/formioupload/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/mnt/d/git_projects/formioupload/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
```

**Comment by sdancer75** [comment]
free version does not support projects....
